[package]
name = "kevboy"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
anyhow = "1.0.68"
eframe = {version = "0.21.3", features = ["persistence"]}
egui = { version = "0.21.0", features = ["serde"] }
egui_extras = "0.21.0"
hashlink = { version = "0.8.1", features = ["serde", "serde_impl"] }
image = "0.24.5"
rfd = "0.10.0"
rodio = "0.17.0"
sdl2 = "0.35.2"
serde = "1.0.152"

[dev-dependencies]
log = "0.4.17"
simple_logger = "2.3.0"
