#[rustfmt::skip]
pub const INSTRUCTIONS: [OpCode; 256] = [
    OpCode {name: "NOP", op_code: 0x00, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD BC, u16", op_code: 0x01, bytes: 3, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD (BC), A", op_code: 0x02, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC BC", op_code: 0x03, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC B", op_code: 0x04, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "DEC BC", op_code: 0x05, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, u8", op_code: 0x06, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLCA", op_code: 0x07, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (a16), SP", op_code: 0x08, bytes: 3, m_cycles: 5, t_cycles: 20},
    OpCode {name: "ADD HL, BC", op_code: 0x09, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD A, (BC)", op_code: 0x0A, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "DEC BC", op_code: 0x0B, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC C", op_code: 0x0C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "DEC C", op_code: 0x0D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, u8", op_code: 0x0E, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRCA", op_code: 0x0F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "STOP", op_code: 0x10, bytes: 2, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD DE, u16", op_code: 0x11, bytes: 3, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD (DE), A", op_code: 0x12, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC DE", op_code: 0x13, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC D", op_code: 0x14, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "DEC D", op_code: 0x15, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, u8", op_code: 0x16, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLA", op_code: 0x17, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "JR s8", op_code: 0x18, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "ADD HL, DE", op_code: 0x19, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD A, (DE)", op_code: 0x1A, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "DEC DE", op_code: 0x1B, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC E", op_code: 0x1C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "DEC E", op_code: 0x1D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, u8", op_code: 0x1E, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRA", op_code: 0x1F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "JR NZ, s8", op_code: 0x20, bytes: 2, m_cycles: 3, t_cycles: 12}, // TODO
    OpCode {name: "LD HL, u16", op_code: 0x21, bytes: 3, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD (HL+), A", op_code: 0x22, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC HL", op_code: 0x23, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC H", op_code: 0x24, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "DEC H", op_code: 0x25, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, u8", op_code: 0x26, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "DAA", op_code: 0x27, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "JR Z, s8", op_code: 0x28, bytes: 2, m_cycles: 3, t_cycles: 12}, // TODO
    OpCode {name: "ADD HL, HL", op_code: 0x29, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD A, (HL+)", op_code: 0x2A, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "DEC HL", op_code: 0x2B, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC L", op_code: 0x2C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "DEC L", op_code: 0x2D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, u8", op_code: 0x2E, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "CPL", op_code: 0x2F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "JR NC, s8", op_code: 0x30, bytes: 2, m_cycles: 3, t_cycles: 12}, // TODO
    OpCode {name: "LD SP, u16", op_code: 0x31, bytes: 3, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD (HL-), A", op_code: 0x32, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC SP", op_code: 0x33, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC (HL)", op_code: 0x34, bytes: 1, m_cycles: 3, t_cycles: 12},
    OpCode {name: "DEC (HL)", op_code: 0x35, bytes: 1, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD (HL), u8", op_code: 0x36, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "SCF", op_code: 0x37, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "JR C, s8", op_code: 0x38, bytes: 2, m_cycles: 3, t_cycles: 12}, // TODO
    OpCode {name: "ADD HL, SP", op_code: 0x39, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD A, (HL-)", op_code: 0x3A, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "DEC SP", op_code: 0x3B, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "INC A", op_code: 0x3C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "DEC A", op_code: 0x3D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, u8", op_code: 0x3E, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "CCF", op_code: 0x3F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, B", op_code: 0x40, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, C", op_code: 0x41, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, D", op_code: 0x42, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, E", op_code: 0x43, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, H", op_code: 0x44, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, L", op_code: 0x45, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD B, (HL)", op_code: 0x46, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD B, A", op_code: 0x47, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, B", op_code: 0x48, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, C", op_code: 0x49, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, D", op_code: 0x4A, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, E", op_code: 0x4B, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, H", op_code: 0x4C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, L", op_code: 0x4D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD C, (HL)", op_code: 0x4E, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD C, A", op_code: 0x4F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, B", op_code: 0x50, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, C", op_code: 0x51, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, D", op_code: 0x52, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, E", op_code: 0x53, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, H", op_code: 0x54, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, L", op_code: 0x55, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD D, (HL)", op_code: 0x56, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD D, A", op_code: 0x57, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, B", op_code: 0x58, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, C", op_code: 0x59, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, D", op_code: 0x5A, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, E", op_code: 0x5B, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, H", op_code: 0x5C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, L", op_code: 0x5D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD E, (HL)", op_code: 0x5E, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD E, A", op_code: 0x5F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, B", op_code: 0x60, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, C", op_code: 0x61, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, D", op_code: 0x62, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, E", op_code: 0x63, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, H", op_code: 0x64, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, L", op_code: 0x65, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD H, (HL)", op_code: 0x66, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD H, A", op_code: 0x67, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, B", op_code: 0x68, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, C", op_code: 0x69, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, D", op_code: 0x6A, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, E", op_code: 0x6B, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, H", op_code: 0x6C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, L", op_code: 0x6D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD L, (HL)", op_code: 0x6E, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD L, A", op_code: 0x6F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (HL), B", op_code: 0x70, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (HL), C", op_code: 0x71, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (HL), D", op_code: 0x72, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (HL), E", op_code: 0x73, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (HL), H", op_code: 0x74, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (HL), L", op_code: 0x75, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "HALT", op_code: 0x76, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (HL), A", op_code: 0x77, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, B", op_code: 0x78, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, C", op_code: 0x79, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, D", op_code: 0x7A, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, E", op_code: 0x7B, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, H", op_code: 0x7C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, L", op_code: 0x7D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD A, (HL)", op_code: 0x7E, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD A, A", op_code: 0x7F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADD A, B", op_code: 0x80, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADD A, C", op_code: 0x81, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADD A, D", op_code: 0x82, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADD A, E", op_code: 0x83, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADD A, H", op_code: 0x84, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADD A, L", op_code: 0x85, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADD A, (HL)", op_code: 0x86, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "ADD A, A", op_code: 0x87, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADC A, B", op_code: 0x88, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADC A, C", op_code: 0x89, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADC A, D", op_code: 0x8A, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADC A, E", op_code: 0x8B, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADC A, H", op_code: 0x8C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADC A, L", op_code: 0x8D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ADC A, (HL)", op_code: 0x8E, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "ADC A, A", op_code: 0x8F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SUB B", op_code: 0x90, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SUB C", op_code: 0x91, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SUB D", op_code: 0x92, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SUB E", op_code: 0x93, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SUB H", op_code: 0x94, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SUB L", op_code: 0x95, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SUB (HL)", op_code: 0x96, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SUB A", op_code: 0x97, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, B", op_code: 0x98, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, C", op_code: 0x99, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, D", op_code: 0x9A, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, E", op_code: 0x9B, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, H", op_code: 0x9C, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, L", op_code: 0x9D, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, (HL)", op_code: 0x9E, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SBC A, A", op_code: 0x9F, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "AND B", op_code: 0xA0, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "AND C", op_code: 0xA1, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "AND D", op_code: 0xA2, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "AND E", op_code: 0xA3, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "AND H", op_code: 0xA4, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "AND L", op_code: 0xA5, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "AND (HL)", op_code: 0xA6, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "AND A", op_code: 0xA7, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR B", op_code: 0xA8, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR C", op_code: 0xA9, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR D", op_code: 0xAA, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR E", op_code: 0xAB, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR H", op_code: 0xAC, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR L", op_code: 0xAD, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR (HL)", op_code: 0xAE, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "XOR A", op_code: 0xAF, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "OR B", op_code: 0xB0, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "OR C", op_code: 0xB1, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "OR D", op_code: 0xB2, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "OR E", op_code: 0xB3, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "OR H", op_code: 0xB4, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "OR L", op_code: 0xB5, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "OR (HL)", op_code: 0xB6, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "OR A", op_code: 0xB7, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP B", op_code: 0xB8, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP C", op_code: 0xB9, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP D", op_code: 0xBA, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP E", op_code: 0xBB, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP H", op_code: 0xBC, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP L", op_code: 0xBD, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP (HL)", op_code: 0xBE, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "CP A", op_code: 0xBF, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "RET NZ", op_code: 0xC0, bytes: 1, m_cycles: 5, t_cycles: 20}, // TODO
    OpCode {name: "POP BC", op_code: 0xC1, bytes: 1, m_cycles: 3, t_cycles: 12},
    OpCode {name: "JP NZ, u16", op_code: 0xC2, bytes: 3, m_cycles: 4, t_cycles: 16}, // TODO
    OpCode {name: "JP u16", op_code: 0xC3, bytes: 3, m_cycles: 4, t_cycles: 16},
    OpCode {name: "CALL NZ, u16", op_code: 0xC4, bytes: 3, m_cycles: 6, t_cycles: 24}, // TODO
    OpCode {name: "PUSH BC", op_code: 0xC5, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "ADD A, u8", op_code: 0xC6, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 0", op_code: 0xC7, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RET Z", op_code: 0xC8, bytes: 1, m_cycles: 5, t_cycles: 20}, // TODO
    OpCode {name: "RET", op_code: 0xC9, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "JP Z, u16", op_code: 0xCA, bytes: 3, m_cycles: 4, t_cycles: 16}, // TODO
    OpCode {name: "0xCB INSTRUCTION WRONG TABLE", op_code: 0xCB, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CALL Z, u16", op_code: 0xCC, bytes: 3, m_cycles: 6, t_cycles: 24}, // TODO
    OpCode {name: "CALL u16", op_code: 0xCD, bytes: 3, m_cycles: 6, t_cycles: 24},
    OpCode {name: "ADC A, u8", op_code: 0xCE, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 1", op_code: 0xCF, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RET NC", op_code: 0xD0, bytes: 1, m_cycles: 5, t_cycles: 20}, // TODO
    OpCode {name: "POP DE", op_code: 0xD1, bytes: 1, m_cycles: 3, t_cycles: 12},
    OpCode {name: "JP NC, u16", op_code: 0xD2, bytes: 3, m_cycles: 4, t_cycles: 16}, // TODO
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xD3, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CALL NC, u16", op_code: 0xD4, bytes: 3, m_cycles: 6, t_cycles: 24}, // TODO
    OpCode {name: "PUSH DE", op_code: 0xD5, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SUB u8", op_code: 0xD6, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 2", op_code: 0xD7, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "RET C", op_code: 0xD8, bytes: 1, m_cycles: 5, t_cycles: 20}, // TODO
    OpCode {name: "RETI", op_code: 0xD9, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "JP C, u16", op_code: 0xDA, bytes: 3, m_cycles: 4, t_cycles: 16}, // TODO
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xDB, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CALL C, u16", op_code: 0xDC, bytes: 3, m_cycles: 6, t_cycles: 24}, // TODO
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xDD, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "SBC A, u8", op_code: 0xDE, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 3", op_code: 0xDF, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "LD (u8), A", op_code: 0xE0, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "POP HL", op_code: 0xE1, bytes: 1, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD (C), A", op_code: 0xE2, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xE3, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xE4, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "PUSH HL", op_code: 0xE5, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "AND u8", op_code: 0xE6, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 4", op_code: 0xE7, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "ADD SP, s8", op_code: 0xE8, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "JP HL", op_code: 0xE9, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "LD (u16), A", op_code: 0xEA, bytes: 3, m_cycles: 4, t_cycles: 16},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xEB, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xEC, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xED, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "XOR u8", op_code: 0xEE, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 5", op_code: 0xEF, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "LD A, (u8)", op_code: 0xF0, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "POP AF", op_code: 0xF1, bytes: 1, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD A, (C)", op_code: 0xF2, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "DI", op_code: 0xF3, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xF4, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "PUSH AF", op_code: 0xF5, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "OR u8", op_code: 0xF6, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 6", op_code: 0xF7, bytes: 1, m_cycles: 4, t_cycles: 16},
    OpCode {name: "LD HL, SP + s8", op_code: 0xF8, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "LD SP, HL", op_code: 0xF9, bytes: 1, m_cycles: 2, t_cycles: 8},
    OpCode {name: "LD A, (u16)", op_code: 0xFA, bytes: 3, m_cycles: 4, t_cycles: 16},
    OpCode {name: "EI", op_code: 0xFB, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xFC, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "ILLEGAL OPCODE", op_code: 0xFD, bytes: 1, m_cycles: 1, t_cycles: 4},
    OpCode {name: "CP u8", op_code: 0xFE, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RST 7", op_code: 0xFF, bytes: 1, m_cycles: 4, t_cycles: 16},
];

#[rustfmt::skip]
pub const CB_INSTRUCTIONS: [OpCode; 256] = [
    OpCode {name: "RLC B", op_code: 0x00, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLC C", op_code: 0x01, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLC D", op_code: 0x02, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLC E", op_code: 0x03, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLC H", op_code: 0x04, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLC L", op_code: 0x05, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RLC (HL)", op_code: 0x06, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RLC A", op_code: 0x07, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRC B", op_code: 0x08, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRC C", op_code: 0x09, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRC D", op_code: 0x0A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRC E", op_code: 0x0B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRC H", op_code: 0x0C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRC L", op_code: 0x0D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RRC (HL)", op_code: 0x0E, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RRC A", op_code: 0x0F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RL B", op_code: 0x10, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RL C", op_code: 0x11, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RL D", op_code: 0x12, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RL E", op_code: 0x13, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RL H", op_code: 0x14, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RL L", op_code: 0x15, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RL (HL)", op_code: 0x16, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RL A", op_code: 0x17, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RR B", op_code: 0x18, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RR C", op_code: 0x19, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RR D", op_code: 0x1A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RR E", op_code: 0x1B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RR H", op_code: 0x1C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RR L", op_code: 0x1D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RR (HL)", op_code: 0x1E, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RR A", op_code: 0x1F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SLA B", op_code: 0x20, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SLA C", op_code: 0x21, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SLA D", op_code: 0x22, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SLA E", op_code: 0x23, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SLA H", op_code: 0x24, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SLA L", op_code: 0x25, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SLA (HL)", op_code: 0x26, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SLA A", op_code: 0x27, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRA B", op_code: 0x28, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRA C", op_code: 0x29, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRA D", op_code: 0x2A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRA E", op_code: 0x2B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRA H", op_code: 0x2C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRA L", op_code: 0x2D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRA (HL)", op_code: 0x2E, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SRA A", op_code: 0x2F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SWAP B", op_code: 0x30, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SWAP C", op_code: 0x31, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SWAP D", op_code: 0x32, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SWAP E", op_code: 0x33, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SWAP H", op_code: 0x34, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SWAP L", op_code: 0x35, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SWAP (HL)", op_code: 0x36, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SWAP A", op_code: 0x37, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRL B", op_code: 0x38, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRL C", op_code: 0x39, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRL D", op_code: 0x3A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRL E", op_code: 0x3B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRL H", op_code: 0x3C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRL L", op_code: 0x3D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SRL (HL)", op_code: 0x3E, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SRL A", op_code: 0x3F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 0, B", op_code: 0x40, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 0, C", op_code: 0x41, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 0, D", op_code: 0x42, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 0, E", op_code: 0x43, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 0, H", op_code: 0x44, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 0, L", op_code: 0x45, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 0, (HL)", op_code: 0x46, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 0, A", op_code: 0x47, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 1, B", op_code: 0x48, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 1, C", op_code: 0x49, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 1, D", op_code: 0x4A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 1, E", op_code: 0x4B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 1, H", op_code: 0x4C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 1, L", op_code: 0x4D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 1, (HL)", op_code: 0x4E, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 1, A", op_code: 0x4F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 2, B", op_code: 0x50, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 2, C", op_code: 0x51, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 2, D", op_code: 0x52, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 2, E", op_code: 0x53, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 2, H", op_code: 0x54, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 2, L", op_code: 0x55, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 2, (HL)", op_code: 0x56, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 2, A", op_code: 0x57, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 3, B", op_code: 0x58, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 3, C", op_code: 0x59, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 3, D", op_code: 0x5A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 3, E", op_code: 0x5B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 3, H", op_code: 0x5C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 3, L", op_code: 0x5D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 3, (HL)", op_code: 0x5E, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 3, A", op_code: 0x5F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 4, B", op_code: 0x60, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 4, C", op_code: 0x61, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 4, D", op_code: 0x62, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 4, E", op_code: 0x63, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 4, H", op_code: 0x64, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 4, L", op_code: 0x65, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 4, (HL)", op_code: 0x66, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 4, A", op_code: 0x67, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 5, B", op_code: 0x68, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 5, C", op_code: 0x69, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 5, D", op_code: 0x6A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 5, E", op_code: 0x6B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 5, H", op_code: 0x6C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 5, L", op_code: 0x6D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 5, (HL)", op_code: 0x6E, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 5, A", op_code: 0x6F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 6, B", op_code: 0x70, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 6, C", op_code: 0x71, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 6, D", op_code: 0x72, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 6, E", op_code: 0x73, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 6, H", op_code: 0x74, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 6, L", op_code: 0x75, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 6, (HL)", op_code: 0x76, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 6, A", op_code: 0x77, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 7, B", op_code: 0x78, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 7, C", op_code: 0x79, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 7, D", op_code: 0x7A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 7, E", op_code: 0x7B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 7, H", op_code: 0x7C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 7, L", op_code: 0x7D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "BIT 7, (HL)", op_code: 0x7E, bytes: 2, m_cycles: 3, t_cycles: 12},
    OpCode {name: "BIT 7, A", op_code: 0x7F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 0, B", op_code: 0x80, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 0, C", op_code: 0x81, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 0, D", op_code: 0x82, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 0, E", op_code: 0x83, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 0, H", op_code: 0x84, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 0, L", op_code: 0x85, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 0, (HL)", op_code: 0x86, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 0, A", op_code: 0x87, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 1, B", op_code: 0x88, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 1, C", op_code: 0x89, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 1, D", op_code: 0x8A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 1, E", op_code: 0x8B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 1, H", op_code: 0x8C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 1, L", op_code: 0x8D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 1, (HL)", op_code: 0x8E, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 1, A", op_code: 0x8F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 2, B", op_code: 0x90, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 2, C", op_code: 0x91, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 2, D", op_code: 0x92, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 2, E", op_code: 0x93, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 2, H", op_code: 0x94, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 2, L", op_code: 0x95, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 2, (HL)", op_code: 0x96, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 2, A", op_code: 0x97, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 3, B", op_code: 0x98, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 3, C", op_code: 0x99, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 3, D", op_code: 0x9A, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 3, E", op_code: 0x9B, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 3, H", op_code: 0x9C, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 3, L", op_code: 0x9D, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 3, (HL)", op_code: 0x9E, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 3, A", op_code: 0x9F, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 4, B", op_code: 0xA0, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 4, C", op_code: 0xA1, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 4, D", op_code: 0xA2, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 4, E", op_code: 0xA3, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 4, H", op_code: 0xA4, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 4, L", op_code: 0xA5, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 4, (HL)", op_code: 0xA6, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 4, A", op_code: 0xA7, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 5, B", op_code: 0xA8, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 5, C", op_code: 0xA9, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 5, D", op_code: 0xAA, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 5, E", op_code: 0xAB, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 5, H", op_code: 0xAC, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 5, L", op_code: 0xAD, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 5, (HL)", op_code: 0xAE, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 5, A", op_code: 0xAF, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 6, B", op_code: 0xB0, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 6, C", op_code: 0xB1, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 6, D", op_code: 0xB2, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 6, E", op_code: 0xB3, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 6, H", op_code: 0xB4, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 6, L", op_code: 0xB5, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 6, (HL)", op_code: 0xB6, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 6, A", op_code: 0xB7, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 7, B", op_code: 0xB8, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 7, C", op_code: 0xB9, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 7, D", op_code: 0xBA, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 7, E", op_code: 0xBB, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 7, H", op_code: 0xBC, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 7, L", op_code: 0xBD, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "RES 7, (HL)", op_code: 0xBE, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "RES 7, A", op_code: 0xBF, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 0, B", op_code: 0xC0, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 0, C", op_code: 0xC1, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 0, D", op_code: 0xC2, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 0, E", op_code: 0xC3, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 0, H", op_code: 0xC4, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 0, L", op_code: 0xC5, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 0, (HL)", op_code: 0xC6, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 0, A", op_code: 0xC7, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 1, B", op_code: 0xC8, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 1, C", op_code: 0xC9, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 1, D", op_code: 0xCA, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 1, E", op_code: 0xCB, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 1, H", op_code: 0xCC, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 1, L", op_code: 0xCD, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 1, (HL)", op_code: 0xCE, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 1, A", op_code: 0xCF, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 2, B", op_code: 0xD0, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 2, C", op_code: 0xD1, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 2, D", op_code: 0xD2, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 2, E", op_code: 0xD3, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 2, H", op_code: 0xD4, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 2, L", op_code: 0xD5, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 2, (HL)", op_code: 0xD6, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 2, A", op_code: 0xD7, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 3, B", op_code: 0xD8, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 3, C", op_code: 0xD9, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 3, D", op_code: 0xDA, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 3, E", op_code: 0xDB, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 3, H", op_code: 0xDC, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 3, L", op_code: 0xDD, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 3, (HL)", op_code: 0xDE, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 3, A", op_code: 0xDF, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 4, B", op_code: 0xE0, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 4, C", op_code: 0xE1, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 4, D", op_code: 0xE2, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 4, E", op_code: 0xE3, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 4, H", op_code: 0xE4, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 4, L", op_code: 0xE5, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 4, (HL)", op_code: 0xE6, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 4, A", op_code: 0xE7, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 5, B", op_code: 0xE8, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 5, C", op_code: 0xE9, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 5, D", op_code: 0xEA, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 5, E", op_code: 0xEB, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 5, H", op_code: 0xEC, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 5, L", op_code: 0xED, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 5, (HL)", op_code: 0xEE, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 5, A", op_code: 0xEF, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 6, B", op_code: 0xF0, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 6, C", op_code: 0xF1, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 6, D", op_code: 0xF2, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 6, E", op_code: 0xF3, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 6, H", op_code: 0xF4, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 6, L", op_code: 0xF5, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 6, (HL)", op_code: 0xF6, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 6, A", op_code: 0xF7, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 7, B", op_code: 0xF8, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 7, C", op_code: 0xF9, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 7, D", op_code: 0xFA, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 7, E", op_code: 0xFB, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 7, H", op_code: 0xFC, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 7, L", op_code: 0xFD, bytes: 2, m_cycles: 2, t_cycles: 8},
    OpCode {name: "SET 7, (HL)", op_code: 0xFE, bytes: 2, m_cycles: 4, t_cycles: 16},
    OpCode {name: "SET 7, A", op_code: 0xFF, bytes: 2, m_cycles: 2, t_cycles: 8},
];

#[derive(Debug, Clone, Copy)]
pub struct OpCode<'a> {
    pub name: &'a str,
    pub op_code: u8,
    pub bytes: u8,
    pub m_cycles: u8,
    pub t_cycles: u8,
}
