name: Rust

on:
  push:
    tags:
      - 'v**'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
      
      - name: Install needed dependencies
        run: sudo apt-get update && sudo apt-get install -y librust-atk-dev libatk1.0-dev libgtk-3-dev libasound2-dev libudev-dev

      - name: Build
        run: cargo build --workspace --release && strip target/release/kevboy && mv target/release/kevboy target/release/kevboy_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/kevboy_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --workspace --release

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: target/release/kevboy.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "x86_64-apple-darwin, aarch64-apple-darwin"

      - name: Build for mac
        run: | 
          cargo build --target=x86_64-apple-darwin --workspace --release
          strip target/x86_64-apple-darwin/release/kevboy
          cargo build --target=aarch64-apple-darwin --workspace --release
          strip target/aarch64-apple-darwin/release/kevboy
          lipo target/x86_64-apple-darwin/release/kevboy target/aarch64-apple-darwin/release/kevboy -create -output kevboy
          mv target/x86_64-apple-darwin/release/kevboy target/release/kevboy_mac_x86
          mv kevboy kevboy_mac_universal

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          files: |
            target/release/kevboy_mac_x86
            kevboy_mac_universal

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
